name: Print Message

on:
  push:
    branches:
      - 'master'      
     #'**'   #run when you push on any branch

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print commit message
        run: |
          echo "Commit message:"
          git log -1 --pretty=%B